---
include:
  # --- Звичайні прошивки (із nice_view) ------------------
  - board: eyelash_corne_left
    shield: nice_view
    snippet: studio-rpc-usb-uart         # ZMK Studio RPC
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_corne_left

  - board: eyelash_corne_right
    shield: nice_view
    artifact-name: eyelash_corne_right   # (можна додати snippet, якщо треба Studio/лог)

  # --- Скидання налаштувань (Settings Reset) --------------
  - board: eyelash_corne_left
    shield: settings_reset
    artifact-name: settings_reset_left

  - board: eyelash_corne_right
    shield: settings_reset
    artifact-name: settings_reset_right

